# Generated by Django 3.2.8 on 2021-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('seat_avail', models.IntegerField()),
                ('fees', models.FloatField()),
                ('joining_end_date', models.DateField()),
                ('joining_start_date', models.DateField()),
            ],
        ),
    ]
