# Generated by Django 3.2.8 on 2021-10-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20211026_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('events_joined', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
