# Generated by Django 3.2.8 on 2021-11-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_usertransaction_transaction_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.events'),
        ),
    ]
