# Generated by Django 3.2.8 on 2021-11-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_usertransaction_transaction_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTransaction',
        ),
    ]
