# Generated by Django 3.2.8 on 2021-11-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_usertransaction_transaction_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
