# Generated by Django 3.2.8 on 2021-11-08 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0021_alter_usertransaction_transaction_event_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsJoined',
            new_name='Booking',
        ),
    ]
