# Generated by Django 3.2.8 on 2021-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_events_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsjoined',
            name='queue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
