# Generated by Django 3.2.8 on 2021-11-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventsjoined_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsjoined',
            name='queue',
        ),
        migrations.AddField(
            model_name='events',
            name='queue_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventsjoined',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventsjoined',
            name='queue_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
